"""Our domain (namespace) for storing config data in home assistant."""
DOMAIN = "openapi_response"

"""Custom config parameters for this component (use in sensor.yaml)."""
CONF_API_BASE = "api_base"
CONF_MODEL = "model"
CONF_PERSONA = "persona"
CONF_KEEPHISTORY = "keep_history"
CONF_TEMPERATURE = "temperature"
CONF_MAX_TOKENS = "max_tokens"
